# Generated by Django 4.0.5 on 2022-06-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
