# Generated by Django 4.0.5 on 2022-06-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessgame', '0003_gameroom_created_at_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='created_at',
        ),
    ]
