# Generated by Django 4.0.5 on 2022-06-28 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chessgame', '0004_remove_gameroom_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
