# Generated by Django 4.0.5 on 2022-06-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessgame', '0005_gameroom_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='room_code',
            new_name='room_id',
        ),
    ]
