# Generated by Django 4.0.5 on 2022-06-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessgame', '0006_rename_room_code_gameroom_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='room_id',
            new_name='room_code',
        ),
    ]
