# Generated by Django 4.0.5 on 2022-07-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessgame', '0007_rename_room_id_gameroom_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
