# Generated by Django 4.0.5 on 2022-07-13 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chessgame', '0008_match_is_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='white_player',
        ),
        migrations.AddField(
            model_name='match',
            name='black_player_user_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='white_player_user_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='black_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_black', to=settings.AUTH_USER_MODEL),
        ),
    ]
